name: CI/CD Angular → GHCR → VPS

on:
  push:
    branches:
      - master   

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      #- name: Ejecutar pruebas
       # run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Construir Angular (producción)
        run: npm run build -- --configuration production

      - name: Iniciar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y enviar imagen a GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/guille117/proyectoclase:latest

      - name: Desplegar en VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/angular-app
            /usr/bin/docker compose pull
            /usr/bin/docker compose up -d --remove-orphans
